import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="Navbar">
          <h1> Apple Fresh </h1>
          <div>
            <Link href="/" className="Navbar_Link">
              {" "}
              홈{" "}
            </Link>
            <Link href="/list" className="Navbar_Link">
              {" "}
              List{" "}
            </Link>
            <Link href="/cart" className="Navbar_Link">
              {" "}
              Cart{" "}
            </Link>
            <Link href="/cart/payment" className="Navbar_Link">
              {" "}
              Payment{" "}
            </Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
